### ISSUE TITLE
Tests fail to compile with `proto3-suite` >= 0.5.0

### ISSUE THREAD

**Issue by Friede80** [awakesecurity/grpc-mqtt#23]
Brought up in #22 

When using `proto3-suite` >= 0.5.0
```
Building test suite 'test' for grpc-mqtt-0.1.0.0..
[ 1 of 16] Compiling Proto.Message    ( gen/test/Proto/Message.hs, /home/matt/Code/grpc-mqtt/dist-newstyle/build/x86_64-linux/ghc-8.10.4/grpc-mqtt-0.1.0.0/t/test/build/test/test-tmp/Proto/Message.o, /home/matt/Code/grpc-mqtt/dist-newstyle/build/x86_64-linux/ghc-8.10.4/grpc-mqtt-0.1.0.0/t/test/build/test/test-tmp/Proto/Message.dyn_o ) [Proto3.Suite.Types changed]
[ 2 of 16] Compiling Proto.Service    ( gen/test/Proto/Service.hs, /home/matt/Code/grpc-mqtt/dist-newstyle/build/x86_64-linux/ghc-8.10.4/grpc-mqtt-0.1.0.0/t/test/build/test/test-tmp/Proto/Service.o, /home/matt/Code/grpc-mqtt/dist-newstyle/build/x86_64-linux/ghc-8.10.4/grpc-mqtt-0.1.0.0/t/test/build/test/test-tmp/Proto/Service.dyn_o ) [Network.GRPC.HighLevel.Server.Unregistered changed]

gen/test/Proto/Service.hs:143:30: error:
    Not in scope: ‘optMaxMetadataSize’
    |
143 |                              optMaxMetadataSize = serverMaxMetadataSize})
    |                              ^^^^^^^^^^^^^^^^^^
```

This looks like its related to this change in `grpc-haskell`: https://github.com/awakesecurity/gRPC-haskell/commit/112777023f475ddd752c954056e679fbca0baa44

**Comment by Friede80** [comment]
Ahh, I think I see what is happening. Our nix overlay pins `grpc-haskell` built with `proto3-suite-0.4.3`, so when I fix `proto3-suite >= 0.5.0`, cabal resolves the dependencies and tries to use `grpc-haskell-0.1.0` because that is the latest version on Hackage.

So I think the only real issue here is that we should add the version contraint `grpc-haskell >= 0.3.0`
